---
title: "Практическое работа 6"
author: "БИСО-01-20 Калбак"
format: 
  md:
    output-file: README.md
---

# Основы обработки данных с помощью R с использованием пакета tidyverse.

## Цель работы

1. Закрепить навыки исследования данных журнала Windows Active Directory;
2. Изучить структуру журнала системы Windows Active Directory;
3. Зекрепить практические навыки использования языка программирования R для
обработки данных;
4. Закрепить знания основных функций обработки данных экосистемы tidyverse
языка R.

## Исходные данные

1.  ОС Windows 10
2.  RStudio Desktop
3.  Интерпретатор языка R 4.3.0
4.  Пакет `dplyr`
5.  

## Общая ситуация

На протяжении долгого времени системные администраторы Доброй Организации
замечали подозрительную активность в домене Windows, но конкретных
доказательств компрометации сети найти не удавалось. К Вам в руки попал файл с
выгрузкой данных из системы SIEM. Помогите выявить факты компрометации.

##Задание

Используя программный пакет `dplyr` языка
программирования R провести анализ журналов и
ответить на вопросы.

## Ход выполнения работы



### Подготовка данных

#### 1. Импортируйте данные в R.


#### 2. Привести датасеты в вид “аккуратных данных”, преобразовать типы столбцов в соответствии с типом данных


#### 3. Просмотрите общую структуру данных с помощью функции `glimpse()`





### Анализ

#### 1. Раскройте датафрейм избавившись от вложенных датафреймов.


#### 2. Минимизируйте количество колонок в датафрейме – уберите колоки с единственным значением параметра.


#### 3.  Какое количество хостов представлено в данном датасете?



#### 4. Подготовьте датафрейм с расшифровкой Windows Event_ID, приведите типы данных к типу их значений.



#### 5. Есть ли в логе события с высоким и средним уровнем значимости? Сколько их?




## Оценка результатов




## Вывод
